name: My GitHub Actions Workflow

on:
  push:
    paths:
      - 'app/**'  # Replace 'special-directory' with your directory's name
  workflow_dispatch:  # This allows manual triggering

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: test
        run: echo "hello"  

      # Add more steps here for your first job

  on_manual_trigger:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: test
        run: echo "Test"

      # Add more steps here for your second job
