name: "App dev"

on:
  push:
    paths:
      - 'app/**'
  workflow_dispatch:    
jobs:
  my_deploy:
    runs-on: [ubuntu-latest]  
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: test
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 548844171305.dkr.ecr.us-east-1.amazonaws.com
      - name: build
        run: docker build -t private-ecr-stage .
      - name: check
        run: docker images
      - name: tag
        run: docker tag private-ecr-stage:latest 548844171305.dkr.ecr.us-east-1.amazonaws.com/private-ecr-stage:v0.4.${{ github.run_number }}
      - name: push
        run: docker push 548844171305.dkr.ecr.us-east-1.amazonaws.com/private-ecr-stage:v0.4.${{ github.run_number }}
      - name: last
        run: docker images
